extraction:
  cpp:
    prepare:
      packages:
      - libssl-dev
      - libmysqlclient-dev
      - libsqlite3-dev
      - libpq-dev
      - unixodbc-dev
      - libldap2-dev
      - liblua5.2-dev
      - libgeoip-dev
      - libcurl4-gnutls-dev
      - libssh-dev
      - libsnmp-dev
      - firebird-dev
      - libhiredis-dev
    configure:
      command:
      - "wget -q -O ptlib.zip https://github.com/willamowius/ptlib/archive/master.zip"
      - "unzip ptlib.zip"
      - "cd ptlib-master"
      - "export PTLIBDIR=$(pwd)"
      - "./configure --enable-ipv6 --disable-odbc --disable-sdl --disable-lua --disable-expat"
      - "make optnoshared"
      - "cd .."
      - "wget -q -O h323plus.zip https://github.com/willamowius/h323plus/archive/master.zip"
      - "unzip h323plus.zip"
      - "cd h323plus-master"
      - "export OPENH323DIR=$(pwd)"
      - "./configure --enable-h235 --enable-h46017 --enable-h46026 --enable-h46019m"
      - "VERBOSE=1 make optnoshared"
      - "cd .."
      - "./configure --enable-h46018 --enable-large-fdset"
    index:
      build_command: "make optnoshared"

